### ISSUE TITLE
Overdispersion as an argument

### ISSUE THREAD

**Issue by koszulordie** [bbglab/omega#25]
The current version of Omega MLE fits a Negative Binomial model with a pre-set overdispersion parameter. Allowing the model to infer overdispersion seemed problematic at testing. However, we could consider allowing the user to input an overdispersion value, thus letting the user to choose between a Poisson (no overdispersion) or a non-Poisson (overdispersed) model.

**Comment by FerriolCalvet** [comment]
I realised now that this issue was already open long ago, do you think we could approach this by adding the dispersion value to the dNdS class objects?
I did this in the branch add-dispersion-arg, I have not tested it yet, but I will do it as soon as you confirm that this is the right parameter to be defined from the command line.

https://github.com/bbglab/omega/compare/main-dev...add-dispersion-arg#diff-3f7b5eaa3e39a0978228d6e7357ce2cfbe75c554e52f6c6d3cf96b84e8c13d40R130-R140

@koszulordie let me know how you see it, I can take care of the testing and merging it later. Thanks!

**Comment by koszulordie** [comment]
I agree with the changes proposed. I added a commit in the same branch to cover the limiting case of dispersion=0 a.k.a. Poisson background model.
